from models import Candidate, Job

candidates: list[Candidate] = [
    Candidate(
        id="CAND-001",
        name="Aarav Mehta",
        role="Senior ML Engineer",
        company="InnovaTech Solutions",
        location="Bengaluru, India",
        experience="7.2 years",
        technicalFit=94,
        skillMatch=92,
        experienceMatch=88,
        recruitability=88,
        careerGrowth=91,
        learningVelocity=85,
        successScore=92,
        skills=["Python", "Embeddings", "Retrieval", "Ranking", "MLOps"],
        reason="Strong production ML experience, high skill overlap, and strong career progression.",
    ),
    Candidate(
        id="CAND-002",
        name="Neha Iyer",
        role="AI Engineer",
        company="DataKraft",
        location="Pune, India",
        experience="5.4 years",
        technicalFit=91,
        skillMatch=89,
        experienceMatch=86,
        recruitability=85,
        careerGrowth=89,
        learningVelocity=88,
        successScore=90,
        skills=["Python", "LLM", "Vector Search", "FastAPI"],
        reason="Good AI engineering background with strong deployment and API experience.",
    ),
    Candidate(
        id="CAND-003",
        name="Rohan Verma",
        role="Search Engineer",
        company="ZepScale",
        location="Hyderabad, India",
        experience="6.1 years",
        technicalFit=87,
        skillMatch=86,
        experienceMatch=84,
        recruitability=92,
        careerGrowth=86,
        learningVelocity=82,
        successScore=89,
        skills=["Search", "Ranking", "Elasticsearch", "Python"],
        reason="Strong search and ranking experience with high recruiter engagement.",
    ),
    Candidate(
        id="CAND-004",
        name="Kavya Nair",
        role="Backend Engineer",
        company="CloudScale",
        location="Remote",
        experience="4.8 years",
        technicalFit=72,
        skillMatch=68,
        experienceMatch=74,
        recruitability=89,
        careerGrowth=94,
        learningVelocity=92,
        successScore=86,
        hiddenGem=True,
        skills=["Docker", "AWS", "Terraform", "FastAPI"],
        reason="Hidden gem with strong backend-to-MLOps transition potential.",
    ),
]

jobs: list[Job] = [
    Job(
        id="JOB-001",
        title="Senior AI Engineer",
        roleCategory="AI / ML",
        location="Bengaluru / Remote",
        experienceRange="5-8 years",
        status="Active",
        candidatesScanned=100000,
        topScore=92,
    ),
    Job(
        id="JOB-002",
        title="ML Platform Engineer",
        roleCategory="MLOps",
        location="Pune",
        experienceRange="4-7 years",
        status="Active",
        candidatesScanned=48200,
        topScore=89,
    ),
]
