/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-error": "#ffffff",
        "surface-container": "#efebff",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#464554",
        "outline-variant": "#c7c4d7",
        "surface-bright": "#fcf8ff",
        "surface-dim": "#dad6ff",
        "surface-container-high": "#e9e5ff",
        "on-secondary-container": "#fffbff",
        surface: "#fcf8ff",
        "on-secondary-fixed": "#0f0069",
        background: "#fcf8ff",
        "surface-tint": "#494bd6",
        secondary: "#4b41e1",
        "primary-fixed": "#e1e0ff",
        "on-primary-fixed-variant": "#2f2ebe",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "secondary-container": "#645efb",
        "on-error-container": "#93000a",
        "inverse-primary": "#c0c1ff",
        "surface-variant": "#e3dfff",
        "on-surface": "#181445",
        "on-tertiary-container": "#f9fdff",
        "surface-container-highest": "#e3dfff",
        "tertiary-container": "#008096",
        "surface-container-low": "#f6f2ff",
        "on-tertiary-fixed": "#001f26",
        "primary-fixed-dim": "#c0c1ff",
        tertiary: "#006577",
        error: "#ba1a1a",
        "tertiary-fixed": "#acedff",
        "on-primary-fixed": "#07006c",
        "error-container": "#ffdad6",
        "secondary-fixed": "#e2dfff",
        "on-background": "#181445",
        primary: "#4648d4",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#3323cc",
        outline: "#767586",
        "inverse-surface": "#2d2a5b",
        "inverse-on-surface": "#f3eeff",
        "primary-container": "#6063ee",
        "secondary-fixed-dim": "#c3c0ff",
        "on-primary-container": "#fffbff",
        "tertiary-fixed-dim": "#4cd7f6",
        "on-tertiary-fixed-variant": "#004e5c",
      },
      spacing: {
        "sidebar-width": "260px",
        "header-height": "64px",
        lg: "24px",
        md: "16px",
        xl: "32px",
        "2xl": "48px",
        sm: "8px",
        xs: "4px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        body: ["Inter", "system-ui", "sans-serif"],
        geist: ["Geist", "Inter", "system-ui", "sans-serif"],
        code: ["JetBrains Mono", "monospace"],
      },
      boxShadow: {
        soft: "0 8px 28px rgba(24, 20, 69, 0.06)",
      },
    },
  },
  plugins: [],
};